name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_dynamic_links:
    path: ../
  firebase_core:
    path: ../../firebase_core/firebase_core
  url_launcher: ^5.1.6

dependency_overrides:
  firebase_core:
    path: ../../firebase_core/firebase_core

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
