name: firebase_dynamic_links
description: Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating
  and handling links across multiple platforms.
version: 0.6.0+2
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  url_launcher: ^5.1.6
  e2e: ^0.6.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasedynamiclinks
        pluginClass: FirebaseDynamicLinksPlugin
      ios:
        pluginClass: FLTFirebaseDynamicLinksPlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
